### ISSUE TITLE
Generate input file list based on the metadata db

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#73] opened 2017-04-19 15:10 UTC
We need to generate the input file list of the basic fusion code based on the metadata db.

**Comment by LandonTClipp** [comment] 2017-04-23 00:39
@davidraila 

Mr. Raila, I cannot get any of your python scripts running on ROGER. I have tried loading the correct python modules however python complains of the error:

```
Traceback (most recent call last):
  File "fusionQuery", line 28, in <module>
    from docopt import docopt
ImportError: No module named docopt
```

Can you please provide instructions on how to properly set up a python environment on ROGER? I cannot continue until this is fixed.

**Comment by kyang2014** [comment] 2017-04-24 15:05
This task the bottleneck for the basicfusion work now. Hope this issue can be resolved soon.

**Comment by LandonTClipp** [comment] 2017-04-24 19:44
The issue with docopt has been resolved.

Solution:
1. Install package at user level using pip:
1. export PYTHONUSERBASE=/path/to/your/dir
1. pip install --user docopt
1. After pip install, make sure your env is updated: export PYTHONPATH=$PYTHONUSERBASE/lib/python2.7/site-packages:$PYTHONPATH

**Comment by LandonTClipp** [comment] 2017-04-25 16:36
I think I understand how the database works. I am currently generating a database for all of the Terra data currently on BW. This will probably take a while because there are a lot of files to process. 

I should note, this DB probably shouldn't be used because file transfers are still in progress, I'm just doing this to see if I fully understand how it works.

**Comment by davidraila** [comment] 2017-04-26 20:01
So is the issue on roger resolved?   I.e. can we close this ticket?

**Comment by LandonTClipp** [comment] 2017-04-26 20:03
The issue is resolved but the task is not, I just need a little more time to complete everything, I ran out of time yesterday.

**Comment by davidraila** [comment] 2017-04-26 20:37
It would be good to work together on this for a few minutes so I understand how you're trying to use this.
For the nearline case, once I have the file-lists gathered from the scripts into the ASTER.list.gz  CERES.list.gz  MISR.list.gz  MODIS.list.gz  MOPITT.list.gz it builds the 180M DB in about 30 seconds.
In the case of online storage in scratch or under /projects or any path really, we just need to generate 
the equivalent lists of files, or even a single big list is fine - they are just partitioned into the per-instrument files for easy updating of one instrument at a time.    Generating the files to build the time-metadata DB should be as simple as a this for the data in BW:/projects/sciteam/jq0/TerraFusion

`find /projects/sciteam/jq0/TerraFusion/oneorbit -type f | gzip -c > /tmp/ff.gz`
 then a build with something along the lines of
`./fusionBuildDB  -o -q --discards=discards.txt --anomalies=errors.txt /tmp/oneorbit.sqlite data/Orbit_Path_Time.txt.gz /tmp/ff.gz`

Then you should be able to 
`. queries.bash
`
and use the query functions.... like I do here:
`
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ allOverlappingOrbit /tmp/oneorbit.sqlite 40111
/projects/sciteam/jq0/TerraFusion/oneorbit/MODIS/MOD03.A2007184.1745.006.2012239144155.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MODIS/MOD021KM.A2007184.1745.006.2014231114122.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/CERES/BDS/CER_BDS_Terra-FM1_Edition3_032040.20070703
/projects/sciteam/jq0/TerraFusion/oneorbit/CERES/BDS/CER_BDS_Terra-FM2_Edition3_032040.20070703
/projects/sciteam/jq0/TerraFusion/oneorbit/MOPITT/MOP01-20070703-L1V3.50.0.he5
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_BF_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_DA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_CA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_BA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AN_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_DF_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AF_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_CF_F03_0024.hdf
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ in /tmp/oneorbit.sqlite 40111
in                          init                        install                     instmodsh                   invprofcheck
indent                      init.lxc                    install-catalog             instrumentOverlappingOrbit  invproj
info                        inotifywait                 install-info                instrumentStartingInOrbit   
infocmp                     inotifywatch                installkernel               intel-microcode2ucode       
infotocap                   insmod                      install-printerdriver       invgeod                     
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ ins /tmp/oneorbit.sqlite 40111
insmod                      install-catalog             installkernel               instmodsh                   instrumentStartingInOrbit
install                     install-info                install-printerdriver       instrumentOverlappingOrbit  
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ instrumentOverlappingOrbit /tmp/oneorbit.sqlite 40111 MOP
/projects/sciteam/jq0/TerraFusion/oneorbit/MOPITT/MOP01-20070703-L1V3.50.0.he5
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ preceedingFile /tmp/oneorbit.sqlite /projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AF_F03_0024.hdf
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ allStartingInOrbit /tmp/oneorbit.sqlite 40111
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ allEndingInOrbit /tmp/oneorbit.sqlite 40111
/projects/sciteam/jq0/TerraFusion/oneorbit/MODIS/MOD03.A2007184.1745.006.2012239144155.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MODIS/MOD021KM.A2007184.1745.006.2014231114122.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_BF_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_DA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_CA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_BA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AN_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AA_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_DF_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_AF_F03_0024.hdf
/projects/sciteam/jq0/TerraFusion/oneorbit/MISR/MISR_AM1_GRP_ELLIPSOID_GM_P022_O040110_CF_F03_0024.hdf
raila@raila:~/src/tfusion/basicFusion/metadata-input (raila-query-wip-rb $%)$ 
`

Once you have the file lists, you can build anywhere with the python prerequisites and sqlite.
Once you've built a DB, you can copy that DB to any machine with sqlite and bash only, python
is only required to build and not used for the queries.

Hope that helps

**Comment by LandonTClipp** [comment] 2017-04-26 20:48
Thanks for the info, I think that's pretty much the way I understood it. Although, I used the "find" command to generate one large file listing, not sure if that was the right way to do it but it seemed to work.

Also I said that I was generating a database on BW, I meant to say that I was doing it for all of the data on ROGER (the entire dataset that we currently have). There were quite a few files that the find command included in the file listing that weren't needed, but it seems that your python script correctly discarded those.

Now in your merge request I see you've made some changes in how queries are interfaced, I think the bash script is very helpful because the sqlite3 commands were very ugly! I don't have time right now to look it all over in detail, I will update this page when I do.

**Comment by LandonTClipp** [comment] 2017-04-26 22:55
I am still getting errors. Here is the exact sequence of steps that I take:

`[clipp@cg-gpu01 metadata-input]$ python fusionBuildDB -o -q --discards=discards.txt --anomalies=errors.txt accesslist.sqlite data/Orbit_Path_Time.txt.gz data/MODIS.list.gz data/ASTER.list.gz data/MOPITT.list.gz data/MISR.list.gz data/CERES.list.gz`

`[clipp@cg-gpu01 metadata-input]$ sqlite3 accesslist.sqlite 'select dir, fname from modis inner join dirs on dirs.id == directory where (select stime from orbits where orbit = '40110' ) <= etime and (select etime from orbits where orbit = '40110' ) >= stime' | tr \| /`

This is the output I get:

`Error: no such table: modis`

I copy-pasted the instructions you had in your README. Why is it saying there is no MODIS table? I look at the discards and I do not see any erroneous MODIS discards. Perhaps I may need to meet with you, I don't understand why this won't work for me.

Here is the exact output during DB build:
```

[clipp@cg-gpu01 metadata-input]$ python fusionBuildDB -o -q --discards=discards.txt --anomalies=errors.txt accesslist.sqlite data/Orbit_Path_Time.txt.gz data/MODIS.list.gz data/ASTER.list.gz data/MOPITT.list.gz data/MISR.list.gz data/CERES.list.gz
Processing file data/MODIS.list.gz, 50000 processed, rate: 40311/s
Processing file data/MODIS.list.gz, 100000 processed, rate: 40786/s
Processing file data/MODIS.list.gz, 150000 processed, rate: 41835/s
Processing file data/MODIS.list.gz, 200000 processed, rate: 39832/s
Processing file data/MODIS.list.gz, 250000 processed, rate: 41993/s
Processing file data/MODIS.list.gz, 300000 processed, rate: 41556/s
Processing file data/MODIS.list.gz, 350000 processed, rate: 41410/s
Processing file data/MODIS.list.gz, 400000 processed, rate: 41897/s
Processing file data/MODIS.list.gz, 450000 processed, rate: 39371/s
Processing file data/MODIS.list.gz, 500000 processed, rate: 43181/s
Processing file data/MODIS.list.gz, 550000 processed, rate: 39775/s
Processing file data/MODIS.list.gz, 600000 processed, rate: 41874/s
Processing file data/MODIS.list.gz, 650000 processed, rate: 40912/s
Processing file data/ASTER.list.gz, 50000 processed, rate: 41433/s
Processing file data/ASTER.list.gz, 100000 processed, rate: 37631/s
Processing file data/ASTER.list.gz, 150000 processed, rate: 39719/s
Processing file data/ASTER.list.gz, 200000 processed, rate: 38685/s
Processing file data/ASTER.list.gz, 250000 processed, rate: 38940/s
Processing file data/ASTER.list.gz, 300000 processed, rate: 40358/s
Processing file data/ASTER.list.gz, 350000 processed, rate: 38232/s
Processing file data/ASTER.list.gz, 400000 processed, rate: 39726/s
Processing file data/ASTER.list.gz, 450000 processed, rate: 37791/s
Processing file data/MISR.list.gz, 50000 processed, rate: 125453/s
Processing file data/MISR.list.gz, 100000 processed, rate: 137556/s
Processing file data/MISR.list.gz, 150000 processed, rate: 138379/s
Processing file data/MISR.list.gz, 200000 processed, rate: 128044/s
Processing file data/MISR.list.gz, 250000 processed, rate: 121478/s
Processing file data/MISR.list.gz, 300000 processed, rate: 123375/s
Processing file data/MISR.list.gz, 350000 processed, rate: 132469/s
Processing file data/MISR.list.gz, 400000 processed, rate: 130138/s
Processing file data/MISR.list.gz, 450000 processed, rate: 128889/s
Processing file data/MISR.list.gz, 500000 processed, rate: 137676/s
Processing file data/MISR.list.gz, 550000 processed, rate: 137884/s
Processing file data/MISR.list.gz, 600000 processed, rate: 124809/s
Processing file data/MISR.list.gz, 650000 processed, rate: 121767/s
Processing file data/MISR.list.gz, 700000 processed, rate: 123699/s
Processing file data/MISR.list.gz, 750000 processed, rate: 129487/s
Processing file data/MISR.list.gz, 800000 processed, rate: 126834/s
Processing file data/MISR.list.gz, 850000 processed, rate: 137496/s
Processing file data/MISR.list.gz, 900000 processed, rate: 138063/s
Processing file data/MISR.list.gz, 950000 processed, rate: 138392/s
Processing file data/MISR.list.gz, 1000000 processed, rate: 122295/s
Processing file data/MISR.list.gz, 1050000 processed, rate: 121396/s
Processing file data/MISR.list.gz, 1100000 processed, rate: 123868/s
Processing file data/MISR.list.gz, 1150000 processed, rate: 129622/s
Processing file data/MISR.list.gz, 1200000 processed, rate: 124677/s
Processing file data/MISR.list.gz, 1250000 processed, rate: 137040/s
Processing file data/MISR.list.gz, 1300000 processed, rate: 137561/s
Processing file data/MISR.list.gz, 1350000 processed, rate: 131155/s
```

**Comment by kyang2014** [comment] 2017-04-27 14:20
Fully agree. Having a short meeting with David is the way to go ☺

**Comment by LandonTClipp** [comment] 2017-04-27 14:37
Yes, I can meet any time today (Thursday) or Friday after 2pm. Let me know Mr. Raila if we can meet anywhere in those times.

**Comment by davidraila** [comment] 2017-04-27 14:52
Use the query support in queries.bash.
The per-instrument tables were merged to support easier queries, but I hadn't updated the readme.
You can see my output above for live examples. [https://github.com/TerraFusion/basicFusion/issues/73#issuecomment-297533823](url), I just updated the README.

If you want modis for 40110 use this in bash:
. queries.bash
instrumentOverlappingOrbit <your-db-file> 40110 MOD

like this, output omitted - line wrap makes a mess

`raila@raila:~/src/tfusion/basicFusion/metadata-input (master $%)$ . ./queries.bash 
raila@raila:~/src/tfusion/basicFusion/metadata-input (master $%)$ instrumentOverlappingOrbit oneorbit.sqlite 40110 MOD`

**Comment by LandonTClipp** [comment] 2017-04-27 15:04
Oh I see, I understand now. I have tried it, I am getting what appears to be correct output. Thanks for the clarification.

**Comment by LandonTClipp** [comment] 2017-04-27 16:05
I am uploading some simple wrapper scripts that generate the DB (using Mr. Raila's scripts) and then generate the inputFiles.txt given an orbit number. So far, the generated list has some files in there that we don't need (for instance, MOD06 files, not sure why those are being transferred to ROGER. The fusionBuildDB script should also not be including those) and there are also some files missing. The missing files are just an artifact of the transfer process. I need to ask Sean what orbits have all the files we need.

[The list here](https://github.com/TerraFusion/basicFusion/blob/master/inputFileDebug/roger_large_input.txt) shows exactly what files we need. 

Also, generated inputFiles.txt does not order the files properly within each instrument, but I have not really done anything to order them properly. I will work on this later.

The scripts I'm uploading are generateDB.sh and genFusionInput.sh. generateDB.sh takes care of the process of making the database using the current data on ROGER. The process takes around 10 minutes. genFusionInput.sh simply takes as an argument the orbit number required and produces an inputFiles.txt file (which as I've stated is not in the correct format, but it's a start). I'll push these to master.

**Comment by davidraila** [comment] 2017-05-01 14:11
I can add a filter to eliminate the MOD06 files and add an ordering element to the
queries - just need to know what order you'd like, by time or other?

**Comment by LandonTClipp** [comment] 2017-05-01 17:34
I got your email. Rather than providing you a list of unneeded files, it might simplify your code if you discard ones that are not on the "approved" list of files we are wanting.

As far as ordering the files, I simply need an ordering that follows this:

https://github.com/TerraFusion/basicFusion/blob/master/inputFileDebug/roger_large_input.txt

I can handle querying each specific instrument, but when I query an individual instrument, it should return the list that follows the order as specified in that example file.

Also if the query returns no files for an instrument, the query should instead return a single line that says: "[instrument] N/A".

**Comment by davidraila** [comment] 2017-05-01 20:32
Closing, as original issue is resolved and additional issues should be posted separately.

**Closed as completed by davidraila** 2017-05-01 20:32 UTC
